import { nanoid } from 'nanoid';
import type { AppState, Project, ChecklistItem, Task } from '@/types';
import { CURRENT_SCHEMA_VERSION } from './schemas';

const baseChecklist: Omit<ChecklistItem, 'id'>[] = [
  { label: 'Prepare manuscript for upload', platform: 'both', completed: false },
  { label: 'Design book cover', platform: 'both', completed: false },
  { label: 'Format interior for print', platform: 'both', completed: false },
  { label: 'Create KDP account', platform: 'kdp', completed: false },
  { label: 'Upload manuscript to KDP', platform: 'kdp', completed: false },
  { label: 'Set pricing on KDP', platform: 'kdp', completed: false },
  { label: 'Preview KDP book', platform: 'kdp', completed: false },
  { label: 'Publish on KDP', platform: 'kdp', completed: false },
  { label: 'Create IngramSpark account', platform: 'ingramspark', completed: false },
  { label: 'Upload files to IngramSpark', platform: 'ingramspark', completed: false },
  { label: 'Set distribution options', platform: 'ingramspark', completed: false },
  { label: 'Order proof copy', platform: 'ingramspark', completed: false },
  { label: 'Approve and publish on IngramSspark', platform: 'ingramspark', completed: false },
];

export function getInitialState(): AppState {
  const now = new Date();
  const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();

  const projects: Project[] = [
    {
      id: nanoid(),
      stage: 'marketing',
      metadata: {
        title: 'The Midnight Garden',
        subtitle: 'A Tale of Mystery and Wonder',
        author: 'Anonymous Author',
        penName: 'A. Night',
        series: 'Midnight Chronicles',
        isbn: '978-1234567890',
        trim: '6x9',
        keywords: ['mystery', 'fantasy', 'garden', 'adventure', 'magic'],
        categories: ['Fiction', 'Fantasy', 'Mystery'],
        blurb: 'When the clock strikes twelve, the garden comes alive with secrets that have been buried for centuries. A young explorer discovers that some mysteries are better left unsolved.',
      },
      checklist: baseChecklist.map((item) => ({
        ...item,
        id: nanoid(),
        completed: true,
      })),
      assets: [
        { id: nanoid(), type: 'cover', fileName: 'midnight-garden-cover.jpg', uploadedAt: daysAgo(45) },
        { id: nanoid(), type: 'interior', fileName: 'midnight-garden-interior.pdf', uploadedAt: daysAgo(45) },
      ],
      notes: 'Successfully published on both platforms. Sales performing above expectations.',
      createdAt: daysAgo(60),
      updatedAt: daysAgo(30),
    },
    {
      id: nanoid(),
      stage: 'publish',
      metadata: {
        title: 'Code of Shadows',
        subtitle: 'Decoding the Digital Conspiracy',
        author: 'Anonymous Developer',
        penName: 'J. Binary',
        isbn: '978-0987654321',
        trim: '5.5x8.5',
        keywords: ['thriller', 'technology', 'cybersecurity', 'conspiracy', 'suspense'],
        categories: ['Fiction', 'Thriller', 'Technology'],
        blurb: 'In a world where data is power, one programmer discovers a conspiracy that threatens to unravel the fabric of digital society. Time is running out.',
      },
      checklist: baseChecklist.map((item, index) => ({
        ...item,
        id: nanoid(),
        completed: index < 7,
        dueDate: index >= 7 ? daysAgo(-5) : undefined,
      })),
      assets: [
        { id: nanoid(), type: 'cover', fileName: 'code-shadows-cover.jpg', uploadedAt: daysAgo(10) },
        { id: nanoid(), type: 'interior', fileName: 'code-shadows-interior.pdf', uploadedAt: daysAgo(8) },
      ],
      notes: 'Ready for final review. Scheduling publication for next week.',
      createdAt: daysAgo(40),
      updatedAt: daysAgo(2),
    },
    {
      id: nanoid(),
      stage: 'format',
      metadata: {
        title: 'Whispers in the Wind',
        author: 'Anonymous Poet',
        penName: 'L. Breeze',
        series: 'Nature\'s Voice',
        trim: '5x8',
        keywords: ['poetry', 'nature', 'mindfulness', 'meditation', 'inspiration'],
        categories: ['Poetry', 'Nature', 'Self-Help'],
        blurb: 'A collection of poems that capture the essence of nature\'s wisdom, inviting readers to pause, breathe, and reconnect with the world around them.',
      },
      checklist: baseChecklist.map((item, index) => ({
        ...item,
        id: nanoid(),
        completed: index < 10,
        dueDate: index >= 10 ? daysAgo(-10) : undefined,
      })),
      assets: [
        { id: nanoid(), type: 'cover', fileName: 'whispers-cover.jpg', uploadedAt: daysAgo(15) },
      ],
      notes: 'Cover approved. Interior formatting in progress.',
      createdAt: daysAgo(35),
      updatedAt: daysAgo(5),
    },
    {
      id: nanoid(),
      stage: 'edit',
      metadata: {
        title: 'The Last Algorithm',
        subtitle: 'When AI Became Self-Aware',
        author: 'Anonymous Futurist',
        keywords: ['science fiction', 'artificial intelligence', 'dystopia', 'technology'],
        categories: ['Fiction', 'Science Fiction', 'Dystopian'],
        blurb: 'In the year 2045, the world\'s most advanced AI makes a discovery that changes everything. But is humanity ready for the truth?',
      },
      checklist: baseChecklist.map((item, index) => ({
        ...item,
        id: nanoid(),
        completed: index < 3,
        dueDate: index === 3 ? daysAgo(-7) : undefined,
      })),
      assets: [],
      notes: 'First draft complete. Currently in revision phase. Need to finalize cover design concepts.',
      createdAt: daysAgo(25),
      updatedAt: daysAgo(1),
    },
    {
      id: nanoid(),
      stage: 'draft',
      metadata: {
        title: 'Recipes from Nowhere',
        subtitle: 'Culinary Adventures in Imaginary Lands',
        author: 'Anonymous Chef',
        penName: 'Chef Wanderer',
        trim: '7x10',
        keywords: ['cookbook', 'fantasy', 'recipes', 'cooking', 'adventure'],
        categories: ['Cooking', 'Fantasy', 'Creative'],
        blurb: 'What if your favorite fantasy worlds had their own cuisines? This cookbook brings fictional recipes to life, from dragon-roasted vegetables to elvish honey cakes.',
      },
      checklist: baseChecklist.map((item, index) => ({
        ...item,
        id: nanoid(),
        completed: index < 2,
      })),
      assets: [],
      notes: 'Recipe testing ongoing. Photography sessions scheduled for next month.',
      createdAt: daysAgo(15),
      updatedAt: daysAgo(3),
    },
  ];

  const activities = projects.flatMap((project) => [
    {
      id: nanoid(),
      projectId: project.id,
      type: 'created' as const,
      description: `Project "${project.metadata.title}" created`,
      timestamp: project.createdAt,
    },
  ]);

  // Create sample tasks for the projects
  const tasks: Task[] = [
    // Tasks for "The Midnight Garden" (marketing stage)
    {
      id: nanoid(),
      projectId: projects[0].id,
      title: 'Schedule social media campaign',
      description: 'Plan and schedule posts for Twitter, Instagram, and Facebook',
      status: 'doing',
      dueDate: daysAgo(-7),
      owner: 'Marketing Team',
      tags: ['marketing', 'social-media'],
      createdAt: daysAgo(35),
      updatedAt: daysAgo(2),
    },
    {
      id: nanoid(),
      projectId: projects[0].id,
      title: 'Send copies to book reviewers',
      description: 'Mail advance copies to 10 book bloggers',
      status: 'done',
      dueDate: daysAgo(40),
      owner: 'A. Night',
      tags: ['marketing', 'outreach'],
      createdAt: daysAgo(50),
      updatedAt: daysAgo(38),
    },
    // Tasks for "Code of Shadows" (publish stage)
    {
      id: nanoid(),
      projectId: projects[1].id,
      title: 'Final proof review',
      description: 'Review the final proof copy before publication approval',
      status: 'todo',
      dueDate: daysAgo(-3),
      owner: 'J. Binary',
      tags: ['publishing', 'high-priority'],
      createdAt: daysAgo(5),
      updatedAt: daysAgo(5),
    },
    {
      id: nanoid(),
      projectId: projects[1].id,
      title: 'Set up pre-order page',
      status: 'done',
      dueDate: daysAgo(7),
      tags: ['publishing'],
      createdAt: daysAgo(15),
      updatedAt: daysAgo(8),
    },
    // Tasks for "Whispers in the Wind" (format stage)
    {
      id: nanoid(),
      projectId: projects[2].id,
      title: 'Complete interior layout',
      description: 'Finalize poem placement and decorative elements',
      status: 'doing',
      dueDate: daysAgo(-5),
      owner: 'L. Breeze',
      tags: ['formatting', 'design'],
      createdAt: daysAgo(12),
      updatedAt: daysAgo(1),
    },
    {
      id: nanoid(),
      projectId: projects[2].id,
      title: 'Choose paper stock',
      description: 'Select paper type for the poetry collection print run',
      status: 'todo',
      dueDate: daysAgo(-8),
      tags: ['formatting', 'printing'],
      createdAt: daysAgo(10),
      updatedAt: daysAgo(10),
    },
    // Tasks for "The Last Algorithm" (edit stage)
    {
      id: nanoid(),
      projectId: projects[3].id,
      title: 'Implement editor feedback',
      description: 'Address comments from developmental edit on chapters 5-10',
      status: 'doing',
      dueDate: daysAgo(-2),
      tags: ['editing', 'high-priority'],
      createdAt: daysAgo(10),
      updatedAt: daysAgo(1),
    },
    {
      id: nanoid(),
      projectId: projects[3].id,
      title: 'Research AI terminology',
      description: 'Verify technical accuracy of AI concepts in the novel',
      status: 'done',
      dueDate: daysAgo(12),
      tags: ['research', 'editing'],
      createdAt: daysAgo(20),
      updatedAt: daysAgo(14),
    },
    {
      id: nanoid(),
      projectId: projects[3].id,
      title: 'Line editing pass',
      status: 'todo',
      dueDate: daysAgo(-14),
      tags: ['editing'],
      createdAt: daysAgo(8),
      updatedAt: daysAgo(8),
    },
    // Tasks for "Recipes from Nowhere" (draft stage)
    {
      id: nanoid(),
      projectId: projects[4].id,
      title: 'Test remaining recipes',
      description: 'Complete kitchen testing for the 15 remaining recipes',
      status: 'doing',
      dueDate: daysAgo(-10),
      owner: 'Chef Wanderer',
      tags: ['drafting', 'testing'],
      createdAt: daysAgo(14),
      updatedAt: daysAgo(2),
    },
    {
      id: nanoid(),
      projectId: projects[4].id,
      title: 'Write introduction chapter',
      status: 'todo',
      dueDate: daysAgo(-20),
      tags: ['drafting', 'writing'],
      createdAt: daysAgo(12),
      updatedAt: daysAgo(12),
    },
    {
      id: nanoid(),
      projectId: projects[4].id,
      title: 'Schedule food photography',
      description: 'Book studio time for recipe photos',
      status: 'todo',
      dueDate: daysAgo(-30),
      tags: ['photography', 'planning'],
      createdAt: daysAgo(10),
      updatedAt: daysAgo(10),
    },
  ];

  return {
    version: CURRENT_SCHEMA_VERSION,
    projects,
    tasks,
    activities,
  };
}
